stages:
  - prepare
  - test
  - lint

variables:
  NODE_ENV: development
  CI: true

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

lint:
  stage: lint
  script:
    - echo "🔍 Running linter..."
    - npm run lint

test:
  stage: test
  script:
    - echo "🧪 Running tests..."
    - npm run test -- --watchAll=false

format-check:
  stage: test
  script:
    - echo "🎨 Checking format..."
    - npm run format:check
